(function(){'use strict';
const el=(s,a={},c=[])=>{const e=document.createElement(s);Object.entries(a).forEach(([k,v])=>{if(k==='class')e.className=v;else if(k==='html')e.innerHTML=v;else e.setAttribute(k,v)});(Array.isArray(c)?c:[c]).forEach(x=>x!=null&&e.appendChild(typeof x==='string'?document.createTextNode(x):x));return e};
const st=JSON.parse(JSON.stringify(npPBv3Admin.config||{})); if(!st.branding) st.branding={company:'',logo:'',primary:'#0B2650',secondary:'#6366f1',accent:'#ec4899',font:'Inter',custom_css:'',powered:false};
const input=(v,a={})=>{const i=document.createElement('input');Object.assign(i,{type:'text',value:v||''},a);return i}; const number=v=>input(v,{type:'number',step:'1'}); const color=v=>input(v||'#0B2650',{type:'color'});
function render(){const app=document.getElementById('np3-admin-app');app.innerHTML='';const head=el('div',{class:'np3-admin-header'},[el('div',{class:'np3-tabs'},[tab('general','Generelt'),tab('bands','Ansattegrupper'),tab('modules','Moduler'),tab('branding','Branding'),tab('pdf','PDF Generator')]),el('div',{class:'np3-actions'},[btn('Nulstil til demo','ghost',reset),btn('Gem ændringer','primary',save)])]);const body=el('div',{class:'np3-admin-body'});app.appendChild(head);app.appendChild(body);show('general');}
const tab=(id,l)=>{const b=el('button',{class:'np3-tab','data-tab':id},l);b.addEventListener('click',()=>show(id));return b}; const btn=(l,v,fn)=>{const b=el('button',{class:'np3-btn '+(v||'')},l);b.addEventListener('click',fn);return b};
function setActive(id){document.querySelectorAll('.np3-tab').forEach(t=>t.classList.toggle('active',t.getAttribute('data-tab')===id))}
function show(id){setActive(id);const b=document.querySelector('.np3-admin-body');b.innerHTML=''; if(id==='general') g(b); if(id==='bands') bands(b); if(id==='modules') mods(b); if(id==='branding') brand(b); if(id==='pdf') pdf(b);}
function g(b){const w=el('div',{class:'np3-card'});w.appendChild(el('h3',{},'Generelle indstillinger'));const r1=el('div',{class:'np3-row'},[el('div',{class:'np3-label'},'Primær farve'),el('div',{class:'np3-ctrl'},[color(st.color),input(st.color,{class:'np3-text'})])]);r1.querySelector('input[type=color]').addEventListener('input',e=>{r1.querySelector('.np3-text').value=e.target.value;st.color=e.target.value});r1.querySelector('.np3-text').addEventListener('input',e=>{st.color=e.target.value;r1.querySelector('input[type=color]').value=e.target.value});const r2=el('div',{class:'np3-row'},[el('div',{class:'np3-label'},'Årlig rabat (%)'),el('div',{class:'np3-ctrl'},[number(st.yearly_discount||0)])]);r2.querySelector('input').addEventListener('input',e=>st.yearly_discount=parseFloat(e.target.value||0));[r1,r2].forEach(x=>w.appendChild(x));b.appendChild(w);}
function bands(b){const w=el('div',{class:'np3-card'});w.appendChild(el('h3',{},'Ansattegrupper'));const list=el('div',{class:'np3-stack'});st.bands=(st.bands||[]);st.bands.forEach((bn,i)=>list.appendChild(row(bn,i)));const add=btn('Tilføj gruppe','ghost',()=>{st.bands.push({label:'',min:0,max:0});show('bands')});w.appendChild(list);w.appendChild(add);b.appendChild(w);function row(bn,i){const r=el('div',{class:'np3-grid-4'}),l=input(bn.label),mi=number(bn.min),ma=number(bn.max),del=el('button',{class:'np3-icon-btn'},'🗑');l.addEventListener('input',e=>bn.label=e.target.value);mi.addEventListener('input',e=>bn.min=parseInt(e.target.value||0));ma.addEventListener('input',e=>bn.max=parseInt(e.target.value||0));del.addEventListener('click',()=>{st.bands.splice(i,1);show('bands')});[l,mi,ma,del].forEach(x=>r.appendChild(x));return r;}}
function mods(b){const w=el('div',{class:'np3-card'});w.appendChild(el('h3',{},'Moduler'));const list=el('div',{class:'np3-stack'});(st.modules||[]).forEach((m,i)=>list.appendChild(block(m,i)));const add=btn('Tilføj modul','ghost',()=>{st.modules=st.modules||[];st.modules.push({name:'',desc:'',prices:(st.bands||[]).map(()=>0)});show('modules')});w.appendChild(list);w.appendChild(add);b.appendChild(w);function block(m,i){const c=el('div',{class:'np3-subcard'}),name=input(m.name),desc=el('textarea',{class:'np3-textarea'},m.desc||'');name.addEventListener('input',e=>m.name=e.target.value);desc.addEventListener('input',e=>m.desc=e.target.value);c.appendChild(el('label',{class:'np3-label-top'},'Modulnavn'));c.appendChild(name);c.appendChild(el('label',{class:'np3-label-top'},'Beskrivelse'));c.appendChild(desc);const grid=el('div',{class:'np3-prices-grid'});if(!Array.isArray(m.prices))m.prices=[];if(m.prices.length<(st.bands||[]).length)m.prices=[...m.prices,...Array((st.bands||[]).length-m.prices.length).fill(0)];(st.bands||[]).forEach((bn,idx)=>{const L=el('div',{class:'np3-price-label'},bn.label||('Bånd '+(idx+1))),F=input(m.prices[idx]??0,{type:'number',step:'1'});F.addEventListener('input',e=>m.prices[idx]=parseFloat(e.target.value||0));grid.appendChild(el('div',{class:'np3-price-row'},[L,F]));});c.appendChild(el('div',{class:'np3-subtitle'},'Priser per ansattegruppe'));c.appendChild(grid);const del=el('button',{class:'np3-icon-btn danger'},'🗑');del.addEventListener('click',()=>{st.modules.splice(i,1);show('modules')});c.appendChild(el('div',{class:'np3-actions-end'},[del]));return c;}}
function brand(b){const w=el('div',{class:'np3-card'});w.appendChild(el('h3',{},'Branding'));[['Firmanavn','company'],['Logo URL','logo']].forEach(([L,K])=>{const r=el('div',{class:'np3-row'},[el('div',{class:'np3-label'},L),el('div',{class:'np3-ctrl'},[input(st.branding[K]||'')])]);r.querySelector('input').addEventListener('input',e=>st.branding[K]=e.target.value);w.appendChild(r)});b.appendChild(w);}
function pdf(b){const w=el('div',{class:'np3-card'});w.appendChild(el('h3',{},'PDF Tilbudsgenerator'));w.appendChild(el('p',{class:'np3-muted'},'PDF downloades fra opsummeringen i beregneren.'));b.appendChild(w);}
async function save(){const fd=new FormData();fd.append('action','np_pb_v3_save');fd.append('nonce',npPBv3Admin.nonce);fd.append('config',JSON.stringify(st));const r=await fetch(npPBv3Admin.ajax,{method:'POST',body:fd});const d=await r.json();toast(d&&d.success?'Gemt ✔':'Fejl ved gemning');}
async function reset(){const fd=new FormData();fd.append('action','np_pb_v3_reset');fd.append('nonce',npPBv3Admin.nonce);const r=await fetch(npPBv3Admin.ajax,{method:'POST',body:fd});const d=await r.json();if(d&&d.success){Object.assign(st,d.data.config);render();toast('Nulstillet ✔')}else toast('Kunne ikke nulstille');}
function toast(m){let t=document.querySelector('.np3-toast');if(!t){t=el('div',{class:'np3-toast'});document.body.appendChild(t);}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
document.addEventListener('DOMContentLoaded',render);
})();